// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (entity_type, entity_id, action, before_snapshot, after_snapshot)
VALUES ($1, $2, $3, $4, $5) RETURNING id, entity_type, entity_id, action, before_snapshot, after_snapshot, created_at
`

type CreateAuditLogParams struct {
	EntityType     string      `json:"entity_type"`
	EntityID       int64       `json:"entity_id"`
	Action         AuditAction `json:"action"`
	BeforeSnapshot []byte      `json:"before_snapshot"`
	AfterSnapshot  []byte      `json:"after_snapshot"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.BeforeSnapshot,
		&i.AfterSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogForEntity = `-- name: ListAuditLogForEntity :many
SELECT id, entity_type, entity_id, action, before_snapshot, after_snapshot, created_at FROM audit_log WHERE entity_type = $1 AND entity_id = $2 ORDER BY created_at DESC
`

type ListAuditLogForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) ListAuditLogForEntity(ctx context.Context, arg ListAuditLogForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.BeforeSnapshot,
			&i.AfterSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
