// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insurance_policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInsurancePolicy = `-- name: CreateInsurancePolicy :one
INSERT INTO insurance_policies (
    ledger_id, insured_name, location, mobile_no, payment_mode, company,
    vehicle_category, vehicle_model, registration_no, policy_no,
    issue_date, expiry_date, sum_assured, od_premium, net_premium, total_premium,
    commission_basis, commission_percentage
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, ledger_id, insured_name, location, mobile_no, payment_mode, company, vehicle_category, vehicle_model, registration_no, policy_no, issue_date, expiry_date, sum_assured, od_premium, net_premium, total_premium, created_at, updated_at, commission_basis, commission_percentage
`

type CreateInsurancePolicyParams struct {
	LedgerID             *int64         `json:"ledger_id"`
	InsuredName          string         `json:"insured_name"`
	Location             *string        `json:"location"`
	MobileNo             *string        `json:"mobile_no"`
	PaymentMode          *string        `json:"payment_mode"`
	Company              string         `json:"company"`
	VehicleCategory      *string        `json:"vehicle_category"`
	VehicleModel         *string        `json:"vehicle_model"`
	RegistrationNo       *string        `json:"registration_no"`
	PolicyNo             *string        `json:"policy_no"`
	IssueDate            pgtype.Date    `json:"issue_date"`
	ExpiryDate           pgtype.Date    `json:"expiry_date"`
	SumAssured           *string        `json:"sum_assured"`
	OdPremium            *string        `json:"od_premium"`
	NetPremium           pgtype.Numeric `json:"net_premium"`
	TotalPremium         pgtype.Numeric `json:"total_premium"`
	CommissionBasis      string         `json:"commission_basis"`
	CommissionPercentage pgtype.Numeric `json:"commission_percentage"`
}

func (q *Queries) CreateInsurancePolicy(ctx context.Context, arg CreateInsurancePolicyParams) (InsurancePolicy, error) {
	row := q.db.QueryRow(ctx, createInsurancePolicy,
		arg.LedgerID,
		arg.InsuredName,
		arg.Location,
		arg.MobileNo,
		arg.PaymentMode,
		arg.Company,
		arg.VehicleCategory,
		arg.VehicleModel,
		arg.RegistrationNo,
		arg.PolicyNo,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.SumAssured,
		arg.OdPremium,
		arg.NetPremium,
		arg.TotalPremium,
		arg.CommissionBasis,
		arg.CommissionPercentage,
	)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.InsuredName,
		&i.Location,
		&i.MobileNo,
		&i.PaymentMode,
		&i.Company,
		&i.VehicleCategory,
		&i.VehicleModel,
		&i.RegistrationNo,
		&i.PolicyNo,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.SumAssured,
		&i.OdPremium,
		&i.NetPremium,
		&i.TotalPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBasis,
		&i.CommissionPercentage,
	)
	return i, err
}

const deleteInsurancePolicy = `-- name: DeleteInsurancePolicy :exec
DELETE FROM insurance_policies WHERE id = $1
`

func (q *Queries) DeleteInsurancePolicy(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteInsurancePolicy, id)
	return err
}

const getInsurancePolicy = `-- name: GetInsurancePolicy :one
SELECT id, ledger_id, insured_name, location, mobile_no, payment_mode, company, vehicle_category, vehicle_model, registration_no, policy_no, issue_date, expiry_date, sum_assured, od_premium, net_premium, total_premium, created_at, updated_at, commission_basis, commission_percentage FROM insurance_policies WHERE id = $1
`

func (q *Queries) GetInsurancePolicy(ctx context.Context, id int64) (InsurancePolicy, error) {
	row := q.db.QueryRow(ctx, getInsurancePolicy, id)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.InsuredName,
		&i.Location,
		&i.MobileNo,
		&i.PaymentMode,
		&i.Company,
		&i.VehicleCategory,
		&i.VehicleModel,
		&i.RegistrationNo,
		&i.PolicyNo,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.SumAssured,
		&i.OdPremium,
		&i.NetPremium,
		&i.TotalPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBasis,
		&i.CommissionPercentage,
	)
	return i, err
}

const listInsuranceCommissionPayouts = `-- name: ListInsuranceCommissionPayouts :many
SELECT id, ledger_id, insured_name, location, mobile_no, payment_mode, company, vehicle_category, vehicle_model, registration_no, policy_no, issue_date, expiry_date, sum_assured, od_premium, net_premium, total_premium, created_at, updated_at, commission_basis, commission_percentage FROM insurance_policies
WHERE issue_date BETWEEN $1 AND $2
  AND ($3::text IS NULL OR company = $3)
ORDER BY company, issue_date, id
`

type ListInsuranceCommissionPayoutsParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	Company  *string     `json:"company"`
}

func (q *Queries) ListInsuranceCommissionPayouts(ctx context.Context, arg ListInsuranceCommissionPayoutsParams) ([]InsurancePolicy, error) {
	rows, err := q.db.Query(ctx, listInsuranceCommissionPayouts, arg.FromDate, arg.ToDate, arg.Company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsurancePolicy
	for rows.Next() {
		var i InsurancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.InsuredName,
			&i.Location,
			&i.MobileNo,
			&i.PaymentMode,
			&i.Company,
			&i.VehicleCategory,
			&i.VehicleModel,
			&i.RegistrationNo,
			&i.PolicyNo,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.SumAssured,
			&i.OdPremium,
			&i.NetPremium,
			&i.TotalPremium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionBasis,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsuranceCompanies = `-- name: ListInsuranceCompanies :many
SELECT DISTINCT company FROM insurance_policies ORDER BY company
`

func (q *Queries) ListInsuranceCompanies(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listInsuranceCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var company string
		if err := rows.Scan(&company); err != nil {
			return nil, err
		}
		items = append(items, company)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsurancePolicies = `-- name: ListInsurancePolicies :many
SELECT id, ledger_id, insured_name, location, mobile_no, payment_mode, company, vehicle_category, vehicle_model, registration_no, policy_no, issue_date, expiry_date, sum_assured, od_premium, net_premium, total_premium, created_at, updated_at, commission_basis, commission_percentage FROM insurance_policies
WHERE ($1::bigint IS NULL OR ledger_id = $1)
  AND (
    $2::text IS NULL OR $2 = '' OR
    insured_name ILIKE '%' || $2 || '%' OR
    registration_no ILIKE '%' || $2 || '%' OR
    policy_no ILIKE '%' || $2 || '%' OR
    mobile_no ILIKE '%' || $2 || '%'
  )
ORDER BY expiry_date DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListInsurancePoliciesParams struct {
	LedgerID *int64  `json:"ledger_id"`
	Query    *string `json:"query"`
	Offset   int32   `json:"offset"`
	Limit    int32   `json:"limit"`
}

func (q *Queries) ListInsurancePolicies(ctx context.Context, arg ListInsurancePoliciesParams) ([]InsurancePolicy, error) {
	rows, err := q.db.Query(ctx, listInsurancePolicies,
		arg.LedgerID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsurancePolicy
	for rows.Next() {
		var i InsurancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.InsuredName,
			&i.Location,
			&i.MobileNo,
			&i.PaymentMode,
			&i.Company,
			&i.VehicleCategory,
			&i.VehicleModel,
			&i.RegistrationNo,
			&i.PolicyNo,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.SumAssured,
			&i.OdPremium,
			&i.NetPremium,
			&i.TotalPremium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionBasis,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsuranceRenewals = `-- name: ListInsuranceRenewals :many
SELECT id, ledger_id, insured_name, location, mobile_no, payment_mode, company, vehicle_category, vehicle_model, registration_no, policy_no, issue_date, expiry_date, sum_assured, od_premium, net_premium, total_premium, created_at, updated_at, commission_basis, commission_percentage FROM insurance_policies
WHERE expiry_date BETWEEN $1 AND $2
  AND ($3::text IS NULL OR company = $3)
ORDER BY company, vehicle_category, expiry_date, id
`

type ListInsuranceRenewalsParams struct {
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	Company  *string     `json:"company"`
}

func (q *Queries) ListInsuranceRenewals(ctx context.Context, arg ListInsuranceRenewalsParams) ([]InsurancePolicy, error) {
	rows, err := q.db.Query(ctx, listInsuranceRenewals, arg.FromDate, arg.ToDate, arg.Company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsurancePolicy
	for rows.Next() {
		var i InsurancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.InsuredName,
			&i.Location,
			&i.MobileNo,
			&i.PaymentMode,
			&i.Company,
			&i.VehicleCategory,
			&i.VehicleModel,
			&i.RegistrationNo,
			&i.PolicyNo,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.SumAssured,
			&i.OdPremium,
			&i.NetPremium,
			&i.TotalPremium,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommissionBasis,
			&i.CommissionPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsuranceVehicleCategories = `-- name: ListInsuranceVehicleCategories :many
SELECT DISTINCT vehicle_category FROM insurance_policies
WHERE vehicle_category IS NOT NULL AND vehicle_category != ''
ORDER BY vehicle_category
`

func (q *Queries) ListInsuranceVehicleCategories(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, listInsuranceVehicleCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var vehicle_category *string
		if err := rows.Scan(&vehicle_category); err != nil {
			return nil, err
		}
		items = append(items, vehicle_category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInsurancePolicy = `-- name: UpdateInsurancePolicy :one
UPDATE insurance_policies SET
    ledger_id = $2, insured_name = $3, location = $4, mobile_no = $5,
    payment_mode = $6, company = $7, vehicle_category = $8, vehicle_model = $9,
    registration_no = $10, policy_no = $11, issue_date = $12, expiry_date = $13,
    sum_assured = $14, od_premium = $15, net_premium = $16, total_premium = $17,
    commission_basis = $18, commission_percentage = $19,
    updated_at = now()
WHERE id = $1 RETURNING id, ledger_id, insured_name, location, mobile_no, payment_mode, company, vehicle_category, vehicle_model, registration_no, policy_no, issue_date, expiry_date, sum_assured, od_premium, net_premium, total_premium, created_at, updated_at, commission_basis, commission_percentage
`

type UpdateInsurancePolicyParams struct {
	ID                   int64          `json:"id"`
	LedgerID             *int64         `json:"ledger_id"`
	InsuredName          string         `json:"insured_name"`
	Location             *string        `json:"location"`
	MobileNo             *string        `json:"mobile_no"`
	PaymentMode          *string        `json:"payment_mode"`
	Company              string         `json:"company"`
	VehicleCategory      *string        `json:"vehicle_category"`
	VehicleModel         *string        `json:"vehicle_model"`
	RegistrationNo       *string        `json:"registration_no"`
	PolicyNo             *string        `json:"policy_no"`
	IssueDate            pgtype.Date    `json:"issue_date"`
	ExpiryDate           pgtype.Date    `json:"expiry_date"`
	SumAssured           *string        `json:"sum_assured"`
	OdPremium            *string        `json:"od_premium"`
	NetPremium           pgtype.Numeric `json:"net_premium"`
	TotalPremium         pgtype.Numeric `json:"total_premium"`
	CommissionBasis      string         `json:"commission_basis"`
	CommissionPercentage pgtype.Numeric `json:"commission_percentage"`
}

func (q *Queries) UpdateInsurancePolicy(ctx context.Context, arg UpdateInsurancePolicyParams) (InsurancePolicy, error) {
	row := q.db.QueryRow(ctx, updateInsurancePolicy,
		arg.ID,
		arg.LedgerID,
		arg.InsuredName,
		arg.Location,
		arg.MobileNo,
		arg.PaymentMode,
		arg.Company,
		arg.VehicleCategory,
		arg.VehicleModel,
		arg.RegistrationNo,
		arg.PolicyNo,
		arg.IssueDate,
		arg.ExpiryDate,
		arg.SumAssured,
		arg.OdPremium,
		arg.NetPremium,
		arg.TotalPremium,
		arg.CommissionBasis,
		arg.CommissionPercentage,
	)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.InsuredName,
		&i.Location,
		&i.MobileNo,
		&i.PaymentMode,
		&i.Company,
		&i.VehicleCategory,
		&i.VehicleModel,
		&i.RegistrationNo,
		&i.PolicyNo,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.SumAssured,
		&i.OdPremium,
		&i.NetPremium,
		&i.TotalPremium,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommissionBasis,
		&i.CommissionPercentage,
	)
	return i, err
}
