// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledgers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLedgerMobileNumber = `-- name: AddLedgerMobileNumber :one
INSERT INTO ledger_mobile_numbers (ledger_id, number) VALUES ($1, $2) RETURNING id, ledger_id, number, added_at
`

type AddLedgerMobileNumberParams struct {
	LedgerID int64  `json:"ledger_id"`
	Number   string `json:"number"`
}

func (q *Queries) AddLedgerMobileNumber(ctx context.Context, arg AddLedgerMobileNumberParams) (LedgerMobileNumber, error) {
	row := q.db.QueryRow(ctx, addLedgerMobileNumber, arg.LedgerID, arg.Number)
	var i LedgerMobileNumber
	err := row.Scan(
		&i.ID,
		&i.LedgerID,
		&i.Number,
		&i.AddedAt,
	)
	return i, err
}

const createLedger = `-- name: CreateLedger :one
INSERT INTO ledgers (name, type, c_o, address) VALUES ($1, $2, $3, $4) RETURNING id, name, type, c_o, address, is_system, merged_into_id, created_at, updated_at
`

type CreateLedgerParams struct {
	Name    string     `json:"name"`
	Type    LedgerType `json:"type"`
	CO      *string    `json:"c_o"`
	Address *string    `json:"address"`
}

func (q *Queries) CreateLedger(ctx context.Context, arg CreateLedgerParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, createLedger,
		arg.Name,
		arg.Type,
		arg.CO,
		arg.Address,
	)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CO,
		&i.Address,
		&i.IsSystem,
		&i.MergedIntoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLedgerIfUnused = `-- name: DeleteLedgerIfUnused :execrows
DELETE FROM ledgers AS lg WHERE lg.id = $1
    AND NOT EXISTS (SELECT 1 FROM transaction_entries te WHERE te.ledger_id = $1)
`

func (q *Queries) DeleteLedgerIfUnused(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLedgerIfUnused, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLedger = `-- name: GetLedger :one
SELECT id, name, type, c_o, address, is_system, merged_into_id, created_at, updated_at FROM ledgers WHERE id = $1
`

func (q *Queries) GetLedger(ctx context.Context, id int64) (Ledger, error) {
	row := q.db.QueryRow(ctx, getLedger, id)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CO,
		&i.Address,
		&i.IsSystem,
		&i.MergedIntoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpeningBalanceLedger = `-- name: GetOpeningBalanceLedger :one
SELECT id, name, type, c_o, address, is_system, merged_into_id, created_at, updated_at FROM ledgers WHERE is_system = TRUE LIMIT 1
`

func (q *Queries) GetOpeningBalanceLedger(ctx context.Context) (Ledger, error) {
	row := q.db.QueryRow(ctx, getOpeningBalanceLedger)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CO,
		&i.Address,
		&i.IsSystem,
		&i.MergedIntoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestMobileNumbersForLedgers = `-- name: LatestMobileNumbersForLedgers :many
SELECT DISTINCT ON (ledger_id) ledger_id, number
FROM ledger_mobile_numbers
WHERE ledger_id = ANY($1::bigint[])
ORDER BY ledger_id, added_at DESC
`

type LatestMobileNumbersForLedgersRow struct {
	LedgerID int64  `json:"ledger_id"`
	Number   string `json:"number"`
}

func (q *Queries) LatestMobileNumbersForLedgers(ctx context.Context, dollar_1 []int64) ([]LatestMobileNumbersForLedgersRow, error) {
	rows, err := q.db.Query(ctx, latestMobileNumbersForLedgers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestMobileNumbersForLedgersRow
	for rows.Next() {
		var i LatestMobileNumbersForLedgersRow
		if err := rows.Scan(&i.LedgerID, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ledgerHasTransactions = `-- name: LedgerHasTransactions :one
SELECT EXISTS(SELECT 1 FROM transaction_entries WHERE ledger_id = $1)
`

func (q *Queries) LedgerHasTransactions(ctx context.Context, ledgerID int64) (bool, error) {
	row := q.db.QueryRow(ctx, ledgerHasTransactions, ledgerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLedgerMobileNumbers = `-- name: ListLedgerMobileNumbers :many
SELECT id, ledger_id, number, added_at FROM ledger_mobile_numbers WHERE ledger_id = $1 ORDER BY added_at DESC
`

func (q *Queries) ListLedgerMobileNumbers(ctx context.Context, ledgerID int64) ([]LedgerMobileNumber, error) {
	rows, err := q.db.Query(ctx, listLedgerMobileNumbers, ledgerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerMobileNumber
	for rows.Next() {
		var i LedgerMobileNumber
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.Number,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeLedger = `-- name: MergeLedger :exec
UPDATE ledgers SET merged_into_id = $2, updated_at = now() WHERE id = $1
`

type MergeLedgerParams struct {
	ID           int64  `json:"id"`
	MergedIntoID *int64 `json:"merged_into_id"`
}

func (q *Queries) MergeLedger(ctx context.Context, arg MergeLedgerParams) error {
	_, err := q.db.Exec(ctx, mergeLedger, arg.ID, arg.MergedIntoID)
	return err
}

const resolveLedgerMergeTarget = `-- name: ResolveLedgerMergeTarget :one
WITH RECURSIVE chain AS (
    SELECT l.id AS id, l.merged_into_id AS merged_into_id FROM ledgers l WHERE l.id = $1
    UNION ALL
    SELECT l2.id AS id, l2.merged_into_id AS merged_into_id FROM ledgers l2 JOIN chain c ON l2.id = c.merged_into_id
)
SELECT c.id FROM chain c WHERE c.merged_into_id IS NULL LIMIT 1
`

func (q *Queries) ResolveLedgerMergeTarget(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, resolveLedgerMergeTarget, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const searchLedgers = `-- name: SearchLedgers :many
SELECT DISTINCT l.id, l.name, l.type, l.c_o, l.address, l.is_system, l.merged_into_id, l.created_at, l.updated_at,
    (SELECT string_agg(m2.number, ', ' ORDER BY m2.added_at DESC)
        FROM ledger_mobile_numbers m2 WHERE m2.ledger_id = l.id) AS mobile_numbers
FROM ledgers l
LEFT JOIN ledger_mobile_numbers m ON m.ledger_id = l.id
WHERE l.merged_into_id IS NULL AND (
    l.name ILIKE '%' || $1 || '%' OR
    l.address ILIKE '%' || $1 || '%' OR
    l.c_o ILIKE '%' || $1 || '%' OR
    m.number ILIKE '%' || $1 || '%'
)
AND ($4::text[] IS NULL OR l.type::text = ANY($4::text[]))
ORDER BY l.name
LIMIT $2 OFFSET $3
`

type SearchLedgersParams struct {
	Column1 *string  `json:"column_1"`
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
	Types   []string `json:"types"`
}

type SearchLedgersRow struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Type          LedgerType         `json:"type"`
	CO            *string            `json:"c_o"`
	Address       *string            `json:"address"`
	IsSystem      bool               `json:"is_system"`
	MergedIntoID  *int64             `json:"merged_into_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MobileNumbers []byte             `json:"mobile_numbers"`
}

func (q *Queries) SearchLedgers(ctx context.Context, arg SearchLedgersParams) ([]SearchLedgersRow, error) {
	rows, err := q.db.Query(ctx, searchLedgers,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Types,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLedgersRow
	for rows.Next() {
		var i SearchLedgersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CO,
			&i.Address,
			&i.IsSystem,
			&i.MergedIntoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MobileNumbers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedger = `-- name: UpdateLedger :one
UPDATE ledgers SET name = $2, c_o = $3, address = $4, type = $5, updated_at = now()
WHERE id = $1 RETURNING id, name, type, c_o, address, is_system, merged_into_id, created_at, updated_at
`

type UpdateLedgerParams struct {
	ID      int64      `json:"id"`
	Name    string     `json:"name"`
	CO      *string    `json:"c_o"`
	Address *string    `json:"address"`
	Type    LedgerType `json:"type"`
}

func (q *Queries) UpdateLedger(ctx context.Context, arg UpdateLedgerParams) (Ledger, error) {
	row := q.db.QueryRow(ctx, updateLedger,
		arg.ID,
		arg.Name,
		arg.CO,
		arg.Address,
		arg.Type,
	)
	var i Ledger
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CO,
		&i.Address,
		&i.IsSystem,
		&i.MergedIntoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
