// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAction string

const (
	AuditActionCreated  AuditAction = "created"
	AuditActionEdited   AuditAction = "edited"
	AuditActionDeleted  AuditAction = "deleted"
	AuditActionMerged   AuditAction = "merged"
	AuditActionImported AuditAction = "imported"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type LedgerType string

const (
	LedgerTypeCash     LedgerType = "cash"
	LedgerTypeBank     LedgerType = "bank"
	LedgerTypeLimit    LedgerType = "limit"
	LedgerTypeCustomer LedgerType = "customer"
	LedgerTypeIncome   LedgerType = "income"
	LedgerTypeExpense  LedgerType = "expense"
	LedgerTypeDiscount LedgerType = "discount"
	LedgerTypeOther    LedgerType = "other"
)

func (e *LedgerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerType(s)
	case string:
		*e = LedgerType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerType: %T", src)
	}
	return nil
}

type NullLedgerType struct {
	LedgerType LedgerType `json:"ledger_type"`
	Valid      bool       `json:"valid"` // Valid is true if LedgerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerType), nil
}

type TransactionType string

const (
	TransactionTypePayment  TransactionType = "payment"
	TransactionTypeReceipt  TransactionType = "receipt"
	TransactionTypeDiscount TransactionType = "discount"
	TransactionTypeIncome   TransactionType = "income"
	TransactionTypeJournal  TransactionType = "journal"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type AuditLog struct {
	ID             int64              `json:"id"`
	EntityType     string             `json:"entity_type"`
	EntityID       int64              `json:"entity_id"`
	Action         AuditAction        `json:"action"`
	BeforeSnapshot []byte             `json:"before_snapshot"`
	AfterSnapshot  []byte             `json:"after_snapshot"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Ledger struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Type         LedgerType         `json:"type"`
	CO           *string            `json:"c_o"`
	Address      *string            `json:"address"`
	IsSystem     bool               `json:"is_system"`
	MergedIntoID *int64             `json:"merged_into_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LedgerMobileNumber struct {
	ID       int64              `json:"id"`
	LedgerID int64              `json:"ledger_id"`
	Number   string             `json:"number"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
}

type Transaction struct {
	ID        int64              `json:"id"`
	Type      TransactionType    `json:"type"`
	TxnDate   pgtype.Date        `json:"txn_date"`
	Narration *string            `json:"narration"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TransactionEntry struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	LedgerID      int64          `json:"ledger_id"`
	Debit         pgtype.Numeric `json:"debit"`
	Credit        pgtype.Numeric `json:"credit"`
}
