// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, expires_at) VALUES ($1, $2) RETURNING token, created_at, expires_at
`

type CreateSessionParams struct {
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Token, arg.ExpiresAt)
	var i Session
	err := row.Scan(&i.Token, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getValidSession = `-- name: GetValidSession :one
SELECT token, created_at, expires_at FROM sessions WHERE token = $1 AND expires_at > now()
`

func (q *Queries) GetValidSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getValidSession, token)
	var i Session
	err := row.Scan(&i.Token, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}
