// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (type, txn_date, narration) VALUES ($1, $2, $3) RETURNING id, type, txn_date, narration, created_at, updated_at
`

type CreateTransactionParams struct {
	Type      TransactionType `json:"type"`
	TxnDate   pgtype.Date     `json:"txn_date"`
	Narration *string         `json:"narration"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.Type, arg.TxnDate, arg.Narration)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TxnDate,
		&i.Narration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionEntry = `-- name: CreateTransactionEntry :one
INSERT INTO transaction_entries (transaction_id, ledger_id, debit, credit)
VALUES ($1, $2, $3, $4) RETURNING id, transaction_id, ledger_id, debit, credit
`

type CreateTransactionEntryParams struct {
	TransactionID int64          `json:"transaction_id"`
	LedgerID      int64          `json:"ledger_id"`
	Debit         pgtype.Numeric `json:"debit"`
	Credit        pgtype.Numeric `json:"credit"`
}

func (q *Queries) CreateTransactionEntry(ctx context.Context, arg CreateTransactionEntryParams) (TransactionEntry, error) {
	row := q.db.QueryRow(ctx, createTransactionEntry,
		arg.TransactionID,
		arg.LedgerID,
		arg.Debit,
		arg.Credit,
	)
	var i TransactionEntry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.LedgerID,
		&i.Debit,
		&i.Credit,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const deleteTransactionEntries = `-- name: DeleteTransactionEntries :exec
DELETE FROM transaction_entries WHERE transaction_id = $1
`

func (q *Queries) DeleteTransactionEntries(ctx context.Context, transactionID int64) error {
	_, err := q.db.Exec(ctx, deleteTransactionEntries, transactionID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, type, txn_date, narration, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TxnDate,
		&i.Narration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ledgerBalance = `-- name: LedgerBalance :one
SELECT COALESCE(SUM(debit), 0)::numeric AS total_debit,
       COALESCE(SUM(credit), 0)::numeric AS total_credit
FROM transaction_entries WHERE ledger_id = $1
`

type LedgerBalanceRow struct {
	TotalDebit  pgtype.Numeric `json:"total_debit"`
	TotalCredit pgtype.Numeric `json:"total_credit"`
}

func (q *Queries) LedgerBalance(ctx context.Context, ledgerID int64) (LedgerBalanceRow, error) {
	row := q.db.QueryRow(ctx, ledgerBalance, ledgerID)
	var i LedgerBalanceRow
	err := row.Scan(&i.TotalDebit, &i.TotalCredit)
	return i, err
}

const ledgerBalanceBefore = `-- name: LedgerBalanceBefore :one
SELECT (COALESCE(SUM(te.debit), 0) - COALESCE(SUM(te.credit), 0))::numeric AS balance
FROM transaction_entries te
JOIN transactions t ON t.id = te.transaction_id
WHERE te.ledger_id = $1 AND t.txn_date < $2
`

type LedgerBalanceBeforeParams struct {
	LedgerID int64       `json:"ledger_id"`
	TxnDate  pgtype.Date `json:"txn_date"`
}

func (q *Queries) LedgerBalanceBefore(ctx context.Context, arg LedgerBalanceBeforeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, ledgerBalanceBefore, arg.LedgerID, arg.TxnDate)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const ledgerStatement = `-- name: LedgerStatement :many
SELECT te.id AS entry_id, t.id AS transaction_id, t.txn_date, t.type, t.narration,
    te.debit, te.credit,
    (SELECT COALESCE(json_agg(json_build_object('ledger_id', l2.id, 'name', l2.name) ORDER BY l2.name), '[]')
        FROM transaction_entries te2
        JOIN ledgers l2 ON l2.id = te2.ledger_id
        WHERE te2.transaction_id = t.id AND te2.ledger_id <> te.ledger_id)::text AS counterparties
FROM transaction_entries te
JOIN transactions t ON t.id = te.transaction_id
WHERE te.ledger_id = $1 AND t.txn_date BETWEEN $2 AND $3
ORDER BY t.txn_date ASC, t.id ASC
`

type LedgerStatementParams struct {
	LedgerID  int64       `json:"ledger_id"`
	TxnDate   pgtype.Date `json:"txn_date"`
	TxnDate_2 pgtype.Date `json:"txn_date_2"`
}

type LedgerStatementRow struct {
	EntryID        int64           `json:"entry_id"`
	TransactionID  int64           `json:"transaction_id"`
	TxnDate        pgtype.Date     `json:"txn_date"`
	Type           TransactionType `json:"type"`
	Narration      *string         `json:"narration"`
	Debit          pgtype.Numeric  `json:"debit"`
	Credit         pgtype.Numeric  `json:"credit"`
	Counterparties string          `json:"counterparties"`
}

func (q *Queries) LedgerStatement(ctx context.Context, arg LedgerStatementParams) ([]LedgerStatementRow, error) {
	rows, err := q.db.Query(ctx, ledgerStatement, arg.LedgerID, arg.TxnDate, arg.TxnDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerStatementRow
	for rows.Next() {
		var i LedgerStatementRow
		if err := rows.Scan(
			&i.EntryID,
			&i.TransactionID,
			&i.TxnDate,
			&i.Type,
			&i.Narration,
			&i.Debit,
			&i.Credit,
			&i.Counterparties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDaybook = `-- name: ListDaybook :many
SELECT id, type, txn_date, narration, created_at, updated_at
FROM transactions
WHERE txn_date BETWEEN $1 AND $2
ORDER BY txn_date DESC, id DESC
LIMIT $3 OFFSET $4
`

type ListDaybookParams struct {
	TxnDate   pgtype.Date `json:"txn_date"`
	TxnDate_2 pgtype.Date `json:"txn_date_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListDaybook(ctx context.Context, arg ListDaybookParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listDaybook,
		arg.TxnDate,
		arg.TxnDate_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TxnDate,
			&i.Narration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionEntries = `-- name: ListTransactionEntries :many
SELECT id, transaction_id, ledger_id, debit, credit FROM transaction_entries WHERE transaction_id = $1 ORDER BY id
`

func (q *Queries) ListTransactionEntries(ctx context.Context, transactionID int64) ([]TransactionEntry, error) {
	rows, err := q.db.Query(ctx, listTransactionEntries, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionEntry
	for rows.Next() {
		var i TransactionEntry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.LedgerID,
			&i.Debit,
			&i.Credit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionEntriesWithLedgerNames = `-- name: ListTransactionEntriesWithLedgerNames :many
SELECT te.id, te.transaction_id, te.ledger_id, te.debit, te.credit, l.name AS ledger_name
FROM transaction_entries te
JOIN ledgers l ON l.id = te.ledger_id
WHERE te.transaction_id = $1
ORDER BY te.id
`

type ListTransactionEntriesWithLedgerNamesRow struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	LedgerID      int64          `json:"ledger_id"`
	Debit         pgtype.Numeric `json:"debit"`
	Credit        pgtype.Numeric `json:"credit"`
	LedgerName    string         `json:"ledger_name"`
}

func (q *Queries) ListTransactionEntriesWithLedgerNames(ctx context.Context, transactionID int64) ([]ListTransactionEntriesWithLedgerNamesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionEntriesWithLedgerNames, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionEntriesWithLedgerNamesRow
	for rows.Next() {
		var i ListTransactionEntriesWithLedgerNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.LedgerID,
			&i.Debit,
			&i.Credit,
			&i.LedgerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionEntriesWithLedgerNamesForTransactions = `-- name: ListTransactionEntriesWithLedgerNamesForTransactions :many
SELECT te.id, te.transaction_id, te.ledger_id, te.debit, te.credit, l.name AS ledger_name
FROM transaction_entries te
JOIN ledgers l ON l.id = te.ledger_id
WHERE te.transaction_id = ANY($1::bigint[])
ORDER BY te.transaction_id, te.id
`

type ListTransactionEntriesWithLedgerNamesForTransactionsRow struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	LedgerID      int64          `json:"ledger_id"`
	Debit         pgtype.Numeric `json:"debit"`
	Credit        pgtype.Numeric `json:"credit"`
	LedgerName    string         `json:"ledger_name"`
}

func (q *Queries) ListTransactionEntriesWithLedgerNamesForTransactions(ctx context.Context, dollar_1 []int64) ([]ListTransactionEntriesWithLedgerNamesForTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionEntriesWithLedgerNamesForTransactions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionEntriesWithLedgerNamesForTransactionsRow
	for rows.Next() {
		var i ListTransactionEntriesWithLedgerNamesForTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.LedgerID,
			&i.Debit,
			&i.Credit,
			&i.LedgerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveLedgerEntries = `-- name: MoveLedgerEntries :exec
UPDATE transaction_entries SET ledger_id = $2 WHERE ledger_id = $1
`

type MoveLedgerEntriesParams struct {
	LedgerID   int64 `json:"ledger_id"`
	LedgerID_2 int64 `json:"ledger_id_2"`
}

func (q *Queries) MoveLedgerEntries(ctx context.Context, arg MoveLedgerEntriesParams) error {
	_, err := q.db.Exec(ctx, moveLedgerEntries, arg.LedgerID, arg.LedgerID_2)
	return err
}

const outstandingLedgers = `-- name: OutstandingLedgers :many
SELECT l.id, l.name, l.type,
    (COALESCE(SUM(te.debit), 0) - COALESCE(SUM(te.credit), 0))::numeric AS balance
FROM ledgers l
JOIN transaction_entries te ON te.ledger_id = l.id
WHERE l.type IN ('customer', 'limit') AND l.merged_into_id IS NULL
GROUP BY l.id, l.name, l.type
HAVING (COALESCE(SUM(te.debit), 0) - COALESCE(SUM(te.credit), 0)) <> 0
ORDER BY l.name
`

type OutstandingLedgersRow struct {
	ID      int64          `json:"id"`
	Name    string         `json:"name"`
	Type    LedgerType     `json:"type"`
	Balance pgtype.Numeric `json:"balance"`
}

func (q *Queries) OutstandingLedgers(ctx context.Context) ([]OutstandingLedgersRow, error) {
	rows, err := q.db.Query(ctx, outstandingLedgers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutstandingLedgersRow
	for rows.Next() {
		var i OutstandingLedgersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET type = $2, txn_date = $3, narration = $4, updated_at = now()
WHERE id = $1 RETURNING id, type, txn_date, narration, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID        int64           `json:"id"`
	Type      TransactionType `json:"type"`
	TxnDate   pgtype.Date     `json:"txn_date"`
	Narration *string         `json:"narration"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Type,
		arg.TxnDate,
		arg.Narration,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TxnDate,
		&i.Narration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
